#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser and the terminal; this wizard tells you exactly\n' "$DIM"
  printf '  what to do and captures the values you confirm. Stop any time with\n'
  printf '  Ctrl-C and re-run later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

TOTAL_STAGES=9

banner "品集｜Q Nexus — Mac Studio 本地部署与运维准备"

# ── Stage 1 · 固定 IP ─────────────────────────────────────────────────────
stage "固定局域网 IP（有线以太网）"
say "本项目将通过有线以太网在 $(_existing Q_NEXUS_BIND_ADDRESS || printf '192.168.60.152') 提供访问。"
say "当前本机网络接口："
for iface in en0 en1 en2 en3; do
  ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
  [[ -n "$ip" ]] && note "  $iface = $ip"
done
gateway=$(route -n get default 2>/dev/null | awk '/gateway:/{print $2}' || true)
[[ -n "$gateway" ]] && note "  默认网关 = $gateway"
say ""
step "打开 系统设置 → 网络 → 以太网，确认 IP 为 192.168.60.152。"
step "若显示为 DHCP 自动获取，请到路由器后台为该网卡 MAC 配置 DHCP 保留（静态地址）。"
if [[ -n "$gateway" ]]; then
  open_url "http://$gateway"
  note "若打不开，浏览器手动访问路由器地址 $gateway"
fi
ask Q_NEXUS_BIND_ADDRESS "确认部署用的局域网 IP（当前默认 192.168.60.152）:"
[[ -n "$Q_NEXUS_BIND_ADDRESS" ]] && write_env Q_NEXUS_BIND_ADDRESS "$Q_NEXUS_BIND_ADDRESS"
pause "确认 IP 已固定后继续"

# ── Stage 2 · .env 密钥与绑定 ────────────────────────────────────────────
stage "生成密钥并写入 .env"
say "数据库密码与备份口令将自动生成强随机值并写入 $ENV_FILE（已被 git 忽略）。"
if [[ -z "$(_existing Q_NEXUS_DB_PASSWORD || true)" ]]; then
  Q_NEXUS_DB_PASSWORD=$(openssl rand -hex 24)
  write_env Q_NEXUS_DB_PASSWORD "$Q_NEXUS_DB_PASSWORD"
else
  say "已存在 Q_NEXUS_DB_PASSWORD，保留现有值。"
fi
if [[ -z "$(_existing BACKUP_PASSPHRASE || true)" ]]; then
  BACKUP_PASSPHRASE=$(openssl rand -base64 24)
  write_env BACKUP_PASSPHRASE "$BACKUP_PASSPHRASE"
else
  say "已存在 BACKUP_PASSPHRASE，保留现有值。"
fi
ask Q_NEXUS_PORT "对外端口（推荐 8080）:" 
write_env Q_NEXUS_PORT "${Q_NEXUS_PORT:-8080}"
write_env Q_NEXUS_HTTPS "0"
ask Q_NEXUS_DATA_DIR "受控数据目录（默认仓库下 .data）:"
write_env Q_NEXUS_DATA_DIR "${Q_NEXUS_DATA_DIR:-$REPO_ROOT/.data}"
note "首次运行会自动创建数据目录。"

# ── Stage 3 · 部署启动与健康检查 ─────────────────────────────────────────
stage "启动 Docker Compose 并检查健康"
say "构建镜像并启动 db / web / proxy（约几分钟）。"
step "确认 Colima 已运行：docker info 无报错；否则先运行 brew services start colima"
if ! docker info >/dev/null 2>&1; then
  warn "Docker 未运行。先启动 Colima 再继续。"
  pause "启动 Colima 后按 Enter 继续"
fi
say "执行：docker compose up --build --detach --wait"
docker compose up --build --detach --wait
say "检查健康端点："
curl -fsS "http://${Q_NEXUS_BIND_ADDRESS}:${Q_NEXUS_PORT}/api/health/live" && echo "  live OK"
curl -fsS "http://${Q_NEXUS_BIND_ADDRESS}:${Q_NEXUS_PORT}/api/health/ready" && echo "  ready OK"
if ! curl -fsS "http://${Q_NEXUS_BIND_ADDRESS}:${Q_NEXUS_PORT}/api/health/live" >/dev/null; then
  warn "局域网地址访问失败：请检查 macOS 防火墙是否放行 Docker/端口，或本机防火墙设置。"
fi
pause "确认两个健康检查都返回 ok 后继续"

# ── Stage 4 · 首位管理员 ─────────────────────────────────────────────────
stage "创建首位管理员（一次性初始化）"
say "该命令是交互式的：密码只从隐藏输入读取，不会出现在命令参数或日志中。"
ask Q_NEXUS_ADMIN_USERNAME "管理员用户名（如 qadmin）:"
say "执行：docker compose --profile operations run --rm bootstrap --username \"$Q_NEXUS_ADMIN_USERNAME\""
step "按提示输入并确认一个强密码（至少 14 位）"
docker compose --profile operations run --rm bootstrap --username "$Q_NEXUS_ADMIN_USERNAME"
write_env Q_NEXUS_ADMIN_USERNAME "$Q_NEXUS_ADMIN_USERNAME"
pause "首位管理员创建完成后继续"

# ── Stage 5 · 第二位管理员 ───────────────────────────────────────────────
stage "创建第二位管理员（网页）"
open_url "http://${Q_NEXUS_BIND_ADDRESS}:${Q_NEXUS_PORT}/login"
step "用首位管理员账号登录；首次登录会要求修改密码"
step "进入 管理 → 账户管理 → 创建账号：角色选 管理员，临时密码 ≥14 位"
step "创建后让该账号完成首次改密（AUTH-11：至少两名管理员）"
pause "确认第二位管理员创建并完成改密后继续"

# ── Stage 6 · 备份目标（移动硬盘） ───────────────────────────────────────
stage "连接备份移动硬盘"
say "插入用于备份的移动硬盘，等待其在访达出现。"
step "检查 /Volumes 下列出的卷："
ls -1 /Volumes 2>/dev/null | sed 's/^/    /' || true
ask BACKUP_TARGET_DIR "备份目录（例如 /Volumes/QNexusBackup/q-nexus-backups）:"
if [[ -z "$BACKUP_TARGET_DIR" ]]; then
  warn "未填写备份目录；跳过写入（可稍后手工补 BACKUP_TARGET_DIR）。"
else
  mkdir -p "$BACKUP_TARGET_DIR"
  write_env BACKUP_TARGET_DIR "$BACKUP_TARGET_DIR"
fi
pause "确认备份目录可写后继续"

# ── Stage 7 · 首次手动备份 + 恢复演练 ────────────────────────────────────
stage "首次手动备份与恢复演练（BKP-06）"
set -a; source "$ENV_FILE"; set +a
step "查询首位管理员用户 ID（写入 .env 供定时备份使用）"
admin_id=$(docker compose exec -T db psql -U q_nexus -d q_nexus -tAc \
  "select id from users where normalized_username='${Q_NEXUS_ADMIN_USERNAME:-}'" | tr -d '[:space:]' || true)
if [[ -n "$admin_id" ]]; then
  note "  管理员用户 ID = $admin_id"
  write_env BACKUP_ADMIN_USER_ID "$admin_id"
else
  warn "未查到管理员 ID，稍后可在数据库查询后补写 BACKUP_ADMIN_USER_ID。"
fi
say "执行手动备份（容器内联数据库转储 + 数据卷 + 加密）："
say "docker compose --profile operations run --rm backup manual \"${BACKUP_ADMIN_USER_ID:-}\""
docker compose --profile operations run --rm backup manual "${BACKUP_ADMIN_USER_ID:-}" || warn "备份命令失败，请查看上方错误"
backup_id=$(docker compose exec -T db psql -U q_nexus -d q_nexus -tAc \
  "select id from backups order by started_at desc limit 1" | tr -d '[:space:]' || true)
if [[ -n "$backup_id" ]]; then
  say "执行恢复演练 dry-run（解包到容器内 /tmp/q-nexus-restore-check）："
  docker compose --profile operations run --rm \
    --entrypoint "npx tsx scripts/restore.ts" \
    backup "$backup_id" --apply /tmp/q-nexus-restore-check || warn "恢复演练失败，请查看上方错误"
else
  warn "未找到备份记录，跳过 dry-run。"
fi
pause "确认备份与恢复演练结果后继续"

# ── Stage 8 · 每日/每周自动备份 ──────────────────────────────────────────
stage "配置每日/每周自动备份"
say "将写入两个 launchd 任务：每日 02:30 与每周日 03:00，调用 scripts/backup.ts。"
if confirm "确认安装自动备份任务？"; then
  mkdir -p "$REPO_ROOT/logs"
  wrapper="$REPO_ROOT/scripts/run-backup-launchd.sh"
  cat > "$wrapper" <<EOF
#!/usr/bin/env bash
set -a; source "$REPO_ROOT/.env"; set +a
cd "$REPO_ROOT"
docker compose --profile operations run --rm backup "\$1" "\$BACKUP_ADMIN_USER_ID" >> "$REPO_ROOT/logs/backup.log" 2>&1
EOF
  chmod +x "$wrapper"
  for spec in "daily|30|2|每日" "weekly|0|3|每周日"; do
    kind="${spec%%|*}"; minute="${spec#*|}"; minute="${minute%%|*}"; hour="${spec#*|*}"; hour="${hour%%|*}"; label="${spec##*|}"
    plist="$HOME/Library/LaunchAgents/com.qnexus.backup-${kind}.plist"
    cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.qnexus.backup-${kind}</string>
  <key>ProgramArguments</key>
  <array><string>${wrapper}</string><string>${kind}</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Minute</key><integer>${minute}</integer><key>Hour</key><integer>${hour}</integer></dict>
  <key>StandardOutPath</key><string>${REPO_ROOT}/logs/backup.log</string>
  <key>StandardErrorPath</key><string>${REPO_ROOT}/logs/backup.log</string>
</dict></plist>
EOF
    launchctl unload "$plist" >/dev/null 2>&1 || true
    launchctl load "$plist"
    note "  已安装 ${label} 备份任务（com.qnexus.backup-${kind}）"
  done
  say "检查任务：launchctl list | grep qnexus"
else
  warn "跳过自动备份安装；可在 runbook 中手工配置 cron/launchd。"
fi

# ── Stage 9 · HTTPS 与交接说明 ────────────────────────────────────────────
stage "HTTPS 与运维交接说明"
say "当前以 HTTP 在内网提供服务（SEC-02）。以下任一情况出现时必须升级 HTTPS（SEC-03）："
step "公司 IT 提供内网域名与证书"
step "开始存放内部敏感资料、开放给品质部以外人员、出现远程访问需求"
note "升级时由 IT 在反向代理前终止 HTTPS，并设置 Q_NEXUS_HTTPS=1 后重启。"
say ""
say "运维交接清单："
step "BACKUP_PASSPHRASE 的保管位置至少两名管理员知情（BKP-04），建议登记在部门密码保险柜"
step "每季度执行一次完整恢复演练（BKP-06），步骤见 docs/operations/ops-runbook.md"
step "日志轮转与更新流程按 ops-runbook.md 执行（OPS-10/12）"
step "上线前按 docs/operations/launch-checklist.md 完成内容与试运行验收"
pause "阅读完成后继续"

finish
